source "https://rubygems.org"

gem "jekyll", "~> 4.3"
gem "webrick"  # Required for Ruby 3.0+

# Themes - disabled to use custom layout
# gem "jekyll-theme-cayman"
# gem "minima"
# gem "just-the-docs"

group :jekyll_plugins do
  gem "jekyll-feed"
  gem "jekyll-seo-tag"
  gem "jekyll-sitemap"
end
